### PR TITLE
content to slot

### PR DESCRIPTION
**Pull request by marcus7777**

### CODE REVIEW

**Comment by zikes** [comment]
The `bower.json` dependencies still list `Polymer/polymer#^1.0.0`, which still uses `<content>`. I'm all in favor of updating the whole component to 2.x, if you'd like to update the dependency graph to accompany it. I don't know what else would be involved in 1.0->2.0, though.

**Comment by marcus7777** [comment]
Slot is supported in 1.9.3, I was hoping to make open-elements.org compatible with hybrid mode. But I will not be upgrading open element.com to 2

**Comment by zikes** [comment]
I see, in that case the dependency would need to be updated to `Polymer/polymer#^1.9.3`. If you can include that in your PR I'll go ahead and merge it in.

**Comment by marcus7777** [comment]
bumped version in The Bower file as well, and updated the other slot how does that look?

**Pull request merged**
